# -*- coding: utf-8 -*-

# 公司基本情况
DB_TABLE_STK_COMPANY_INFO = "stock_company_info"

# 员工情况
DB_TABLE_STK_EMPLOYEE_INFO = "stock_employee_info"

# 十大流通股东
DB_TABLE_STK_SHAREHOLDER_FLOATING_TOP10 = "stock_shareholder_floating_top10"

# 十大股东
DB_TABLE_STK_SHAREHOLDER_TOP10 = "stock_shareholder_top10"

# 员工情况
DB_TABLE_STK_EMPLOYEE_INFO = "stock_employee_info"

# 管理人员任职信息
DB_TABLE_STK_MANAGEMENT_INFO = "stock_management_info"

# 公募基金主体信息
DB_TABLE_FUND_MAIN_INFO = "fund_main_info"

NEO4J_LABEL_COMPANY = "公司"

NEO4J_LABEL_INDUSTRY = "行业"
NEO4J_LABEL_EXCHANGE = "交易市场"
NEO4J_LABEL_STOCK = "股票"
NEO4J_LABEL_UNLISTEDCOMPANY = "上市公司"
NEO4J_RELTYPE_SUBINDUSTRY = "子行业"
NEO4J_RELTYPE_STOCK_CODE = "证券代码"

NEO4J_LABEL_FUND = "基金"
NEO4J_RELTYPE_FUND_CODE = "基金代码"
NEO4J_RELTYPE_FUND_SNAME = "简称"
NEO4J_RELTYPE_FUND_ADVISOR = "管理人"
NEO4J_RELTYPE_FUND_TRUSTEE = "托管人"
NEO4J_RELTYPE_FUND_MODE = "运作方式"
NEO4J_RELTYPE_FUND_ASSET_TYPE = "投资标的类型"
NEO4J_RELTYPE_FUND_START_TIME = "成立时间"
NEO4J_RELTYPE_FUND_END_TIME = "结束时间"
