[default]
NEO4J_URL = ''
NEO4J_USER = ''
NEO4J_PASSWD = ''

TUSHARE_TOKEN = ''
JOINQUANT_USER = ''
JOINQUANT_PASSWD = ''

[development]
NEO4J_URL = ''
NEO4J_USER = ''
NEO4J_PASSWD = ''

TUSHARE_TOKEN = ''
JOINQUANT_USER = ''
JOINQUANT_PASSWD = ''

[production]
NEO4J_URL = ''
NEO4J_USER = ''
NEO4J_PASSWD = ''

TUSHARE_TOKEN = ''
JOINQUANT_USER = ''
JOINQUANT_PASSWD = ''

[testing]
NEO4J_URL = ''
NEO4J_USER = ''
NEO4J_PASSWD = ''

TUSHARE_TOKEN = ''
JOINQUANT_USER = ''
JOINQUANT_PASSWD = ''

[global]
